package scom.antony.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ANTONY_FLEX_LIST_DAO_W.
 */
public class AntonyFlexListDaoW {

    /** Not-null value. */
    private String folderid;
    /** Not-null value. */
    private String fid;
    private byte[] data;

    public AntonyFlexListDaoW() {
    }

    public AntonyFlexListDaoW(String folderid, String fid, byte[] data) {
        this.folderid = folderid;
        this.fid = fid;
        this.data = data;
    }

    /** Not-null value. */
    public String getFolderid() {
        return folderid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFolderid(String folderid) {
        this.folderid = folderid;
    }

    /** Not-null value. */
    public String getFid() {
        return fid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFid(String fid) {
        this.fid = fid;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

}
