package scom.antony.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ANTONY_OBJECT_DAO_W.
 */
public class AntonyObjectDaoW {

    private int type;
    private byte[] data;
    private long objectId;
    private long addinId;

    public AntonyObjectDaoW() {
    }

    public AntonyObjectDaoW(int type, byte[] data, long objectId, long addinId) {
        this.type = type;
        this.data = data;
        this.objectId = objectId;
        this.addinId = addinId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    public long getObjectId() {
        return objectId;
    }

    public void setObjectId(long objectId) {
        this.objectId = objectId;
    }

    public long getAddinId() {
        return addinId;
    }

    public void setAddinId(long addinId) {
        this.addinId = addinId;
    }

}
