package scom.antony.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ANTONY_ANDROID_TRANSACTION.
 */
public class AntonyAndroidTransaction {

    private long tAddinID;
    private long tObjectID;
    private Integer tType;

    public AntonyAndroidTransaction() {
    }

    public AntonyAndroidTransaction(long tAddinID, long tObjectID, Integer tType) {
        this.tAddinID = tAddinID;
        this.tObjectID = tObjectID;
        this.tType = tType;
    }

    public long getTAddinID() {
        return tAddinID;
    }

    public void setTAddinID(long tAddinID) {
        this.tAddinID = tAddinID;
    }

    public long getTObjectID() {
        return tObjectID;
    }

    public void setTObjectID(long tObjectID) {
        this.tObjectID = tObjectID;
    }

    public Integer getTType() {
        return tType;
    }

    public void setTType(Integer tType) {
        this.tType = tType;
    }

}
